version: '3'

services:
    app:
        container_name: portfolio_tracker
        image: portfolio_tracker
        build:
            dockerfile: ./Dockerfile
            context: .
        environment:
            - PORT
        ports:
            - $PORT:$PORT