version: '3'

services:
    app:
        image: streamlit-tracker-docker
        build:
            dockerfile: ./Dockerfile
            context: .
        #env_file: .env
        environment:
            - PORT=$PORT
        ports:
            - $PORT:$PORT
        #volumes:
        #    - ./app:/usr/app/src/