version: '3'

services:
    app:
        container_name: portfolio_tracker
        image: portfolio_tracker
        build:
            dockerfile: ./Dockerfile
            context: .
        environment:
            - PORT=5050
        ports:
            - 5050:5050